### ISSUE TITLE
Invalid Argument

### ISSUE THREAD

**Issue by dang1507** [thisiscam/math-with-slack#21] opened 2021-03-15 17:02 UTC
Several versions of Slack are installed.
0) c:\Users\myusername\AppData\Local\slack\app-4.13.0\resources\app.asar <== (default)
1) c:\Users\myusername\AppData\Local\slack\app-4.12.2\resources\app.asar
Choose from above:0

Using Slack installation at: c:\Users\myusername\AppData\Local\slack\app-4.13.0\resources\app.asar

Downloading MathJax...100%, 4.4 MB / 4.4 MB, 1488.4 KB/s, 3.0 secc

Traceback (most recent call last):
  File "C:\Users\myusername\AppData\Local\slack\SlackLateX\math-with-slack.py", line 501, in <module>
    open(app_path, mode='wb') as new_app_fp:

OSError: [Errno 22] Invalid argument: 'c:\\Users\\myusername\\AppData\\Local\\slack\\app-4.13.0\\resources\\app.asar'

**Comment by thisiscam** [comment] 2021-03-15 17:15
Which version of math-with-slack are you using? 
Is it the release version for Windows or the one on `master` branch?

**Comment by thisiscam** [comment] 2021-03-15 17:47
In either case, I have just updated the repo to give better error message. 
Please try again with the updated version and report back if it's still not working for you?

**Comment by thisiscam** [comment] 2021-03-18 01:06
Closing. Assuming this is a duplicate of #18. 
Error message should be better reported now.

**Closed as completed by thisiscam** 2021-03-18 01:06 UTC

**Comment by dang1507** [comment] 2021-03-18 11:56
I just saw this. I'll give it a try and let you know. I've been using the
master branch.

**Comment by dang1507** [comment] 2021-03-18 12:05
Worked like a charm.

Thank you!
